version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      slack-sdk:
        patterns: ['com.slack.api:*']
      slf4j:
        patterns: ['org.slf4j:*']
      byte-buddy:
        patterns: ['net.bytebuddy:*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
