# Create a bot at https://my.slack.com/services/new/bot and paste token here.

slack:
  enabled: true
  token: ""
  channel: ""
  icon: "https://logo.clearbit.com/minecraft.net"
  debug: false

i18n:
  botName: "Minecraft"
  connected: ":white_check_mark: Online"
  disconnected: ":x: Offline"
  joinedGame: "_Joined the game_"
  leftGame: "_Left the game_"
  advancementDone: ":trophy: Has made the advancement "
  death: ":skull: "
